# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-24 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20160806_2050'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=20, verbose_name='留言')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='日期')),
            ],
            options={
                'db_table': 'message',
            },
        ),
    ]
